spring.application.name=nexus-ai

# 1. Configuración de la Conexión (El "Puente")
# Nota: Usamos localhost:5433 porque es el túnel que abrimos en Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/nexus_database
spring.datasource.username=user
spring.datasource.password=password

# 2. Configuración de JPA / Hibernate (El "Traductor")
# 'update' hará que las tablas se creen solas en pgAdmin al arrancar la app
spring.jpa.hibernate.ddl-auto=create-drop
# Esto nos permite ver en la consola el SQL que Spring genera por nosotros
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Dialecto específico para Postgres 17
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=oRF4GuojrctGhpicxbHFmCCMPf3xqzBrNheKZLGQjNw=
jwt.expiration=86400000

gemini.api.key=AIzaSyA97SeCDCpRAK_zcqbg5SyQumF--vsX1HI
